// Legal document content — Privacy Policy, Terms of Service, Disclaimers, and
// the Data Deletion Policy — authored once here in English and Romanian, and
// rendered by BOTH the in-app "About & Legal" sheet (see app.js) and the
// standalone public pages (privacy.html, terms.html, disclaimers.html,
// data-deletion.html). Single source of truth so the native sheet and the
// public web pages Google Play requires can never drift out of sync with
// each other. Deliberately does not import i18n.js: the standalone pages are
// plain documents that don't load the rest of the app's module graph, and
// the in-app sheet reads its own language directly from i18n.js's
// getLanguage() instead (see app.js).
//
// Content only — no HTML escaping is applied when rendering because every
// string below is authored here, not user input.

const LAST_UPDATED = "2026-08-11";
const CONTACT_EMAIL = "condrea.andrey777@gmail.com";
const DEVELOPER_NAME = "Condrea Andrei";

function p(sections) {
  return sections;
}

export const LEGAL_DOCS = {
  privacy: {
    en: {
      title: "Privacy Policy",
      sections: p([
        {
          paragraphs: [
            `This Privacy Policy explains what data Iron Log ("the app", "we", "our") collects, how it is used and stored, and what choices you have. Iron Log is developed and operated by <strong>${DEVELOPER_NAME}</strong>. By creating an account you agree to the collection and use of information as described here.`,
          ],
        },
        {
          heading: "Information we collect",
          paragraphs: ["When you create an account and use Iron Log, we collect:"],
          list: [
            "<strong>Account data</strong> — your email address and password (handled entirely by Supabase Auth; we never see or store your raw password), plus an optional display name and profile photo.",
            "<strong>Health &amp; fitness data you enter</strong> — food and water logs, body weight, body measurements, workout logs, and your daily calorie/macro targets.",
            "<strong>AI Coach conversations</strong> — messages you send to the in-app AI Coach chat, so it can respond with context about your logged data.",
            "<strong>Food photos, temporarily</strong> — a photo you take or upload to scan a meal (see \"How AI food scanning works\" below).",
            "<strong>Basic technical data</strong> — your device's timezone (to know when \"today\" starts and ends for you) and standard request metadata (e.g. timestamps) generated by using the API.",
          ],
        },
        {
          heading: "How AI food scanning works — your photos are not saved",
          paragraphs: [
            "When you scan a meal, the photo is sent directly to Google's Gemini AI API for analysis and is <strong>processed in memory only</strong>. Iron Log's backend does not write the image to disk or to our database at any point — it is forwarded to Gemini, the nutrition estimate is read back, and the image data is then discarded. Only the AI's text output that you choose to save (food name, estimated calories, and macros) is stored, as a normal food log entry, exactly like a manual entry you'd type in yourself.",
            "The same applies to barcode scanning, which uses the free Open Food Facts database and never touches Gemini or sends your photo anywhere — only the scanned barcode number is sent.",
          ],
        },
        {
          heading: "How we use your data",
          list: [
            "To provide the core features of the app: logging, dashboards, trends, streaks, and progress charts.",
            "To calculate suggested calorie/macro targets and AI-estimated nutrition values.",
            "To respond to you in the AI Coach chat feature.",
            "To enforce fair use of our shared AI quota and to keep the service secure and reliable (rate limiting).",
            "To generate a PDF export of your own data when you request one.",
          ],
        },
        {
          heading: "Where your data is stored",
          paragraphs: [
            "Your account and logged data are stored in <strong>Supabase</strong> (a hosted PostgreSQL database and authentication provider). Our backend server runs on <strong>Render</strong>. All traffic between your device, our backend, and Supabase is encrypted in transit (HTTPS/TLS). Database access is protected by per-user Row Level Security policies and, on the backend, every query is explicitly scoped to your own account — no other user's data is ever readable from yours.",
          ],
        },
        {
          heading: "Third-party services we use",
          list: [
            "<strong>Supabase</strong> — authentication and database hosting.",
            "<strong>Google Gemini API</strong> — AI food-photo scanning and the AI Coach chat feature.",
            "<strong>Render</strong> — backend hosting.",
            "<strong>Open Food Facts</strong> — free, keyless barcode lookups (only the barcode number is sent, no account data).",
            "<strong>Cloudflare Turnstile</strong> — an optional anti-bot check that may appear on sign-up.",
            "<strong>Sentry</strong> — optional backend-only error tracking to help us fix bugs; it never runs in the app itself.",
          ],
        },
        {
          heading: "How long we keep your data",
          paragraphs: [
            "Food and water logs are automatically deleted after <strong>7 days</strong> on a rolling basis — this is a deliberate design choice, not a bug. Weight logs are kept indefinitely so you can see a long-term trend, since that's the point of tracking weight. Your account, targets, and saved meals are kept until you delete them or delete your account.",
          ],
        },
        {
          heading: "Your rights and choices",
          list: [
            "<strong>Export</strong> — download a PDF of your own logs at any time from Settings → Your data.",
            "<strong>Correct</strong> — edit or delete any individual log entry directly in the app.",
            "<strong>Delete</strong> — clear your history or delete your account entirely at any time; see our Data Deletion Policy for exactly what each option does.",
            "<strong>Opt out</strong> — reminder notifications are entirely opt-in and can be turned off at any time in Settings.",
          ],
        },
        {
          heading: "Children's privacy",
          paragraphs: ["Iron Log is not directed at children under 16, and we do not knowingly collect data from anyone under that age."],
        },
        {
          heading: "International data transfers",
          paragraphs: ["Because our infrastructure providers (Supabase, Render, Google) operate global infrastructure, your data may be processed in a country other than your own."],
        },
        {
          heading: "Changes to this policy",
          paragraphs: ["We may update this policy from time to time. The \"Last updated\" date at the top reflects the most recent revision."],
        },
        {
          heading: "Contact us",
          paragraphs: [`Questions about this policy or your data? Email <a href="mailto:${CONTACT_EMAIL}">${CONTACT_EMAIL}</a>.`],
        },
      ]),
    },
    ro: {
      title: "Politica de confidențialitate",
      sections: p([
        {
          paragraphs: [
            `Această Politică de confidențialitate explică ce date colectează Iron Log ("aplicația", "noi"), cum sunt folosite și stocate, și ce opțiuni ai. Iron Log este dezvoltată și operată de <strong>${DEVELOPER_NAME}</strong>. Prin crearea unui cont, ești de acord cu colectarea și utilizarea informațiilor descrise aici.`,
          ],
        },
        {
          heading: "Ce date colectăm",
          paragraphs: ["Când creezi un cont și folosești Iron Log, colectăm:"],
          list: [
            "<strong>Date de cont</strong> — adresa ta de email și parola (gestionate integral de Supabase Auth; noi nu vedem și nu stocăm parola ta în clar), plus un nume de afișare și o poză de profil opționale.",
            "<strong>Date de sănătate și fitness introduse de tine</strong> — jurnale de mese și apă, greutate corporală, măsurători corporale, jurnale de antrenamente și obiectivele tale zilnice de calorii/macronutrienți.",
            "<strong>Conversațiile cu AI Coach</strong> — mesajele trimise către chat-ul AI Coach din aplicație, pentru ca acesta să răspundă cu context despre datele tale înregistrate.",
            "<strong>Fotografii cu mese, temporar</strong> — o fotografie pe care o faci sau o încarci pentru a scana o masă (vezi „Cum funcționează scanarea AI a alimentelor” mai jos).",
            "<strong>Date tehnice de bază</strong> — fusul orar al dispozitivului tău (pentru a ști când începe și se termină „azi” pentru tine) și metadate standard de cerere (ex. marcaje de timp) generate prin folosirea API-ului.",
          ],
        },
        {
          heading: "Cum funcționează scanarea AI a alimentelor — fotografiile tale nu sunt salvate",
          paragraphs: [
            "Când scanezi o masă, fotografia este trimisă direct către API-ul Gemini AI al Google pentru analiză și este <strong>procesată exclusiv în memorie</strong>. Backend-ul Iron Log nu scrie imaginea pe disc sau în baza noastră de date în niciun moment — este trimisă către Gemini, se preia estimarea nutrițională, iar apoi datele imaginii sunt eliminate. Doar rezultatul text al AI-ului pe care alegi să-l salvezi (numele alimentului, caloriile estimate și macronutrienții) este stocat, ca o înregistrare normală, exact ca o introducere manuală.",
            "Același lucru este valabil și pentru scanarea codurilor de bare, care folosește baza de date gratuită Open Food Facts și nu implică niciodată Gemini și nici nu trimite fotografia ta nicăieri — se trimite doar numărul codului de bare scanat.",
          ],
        },
        {
          heading: "Cum folosim datele tale",
          list: [
            "Pentru a oferi funcțiile de bază ale aplicației: înregistrare, tablouri de bord, tendințe, serii de zile și grafice de progres.",
            "Pentru a calcula obiectivele sugerate de calorii/macronutrienți și valorile nutriționale estimate de AI.",
            "Pentru a-ți răspunde în funcția de chat AI Coach.",
            "Pentru a aplica o utilizare echitabilă a cotei noastre partajate de AI și pentru a menține serviciul sigur și fiabil (limitare de rată).",
            "Pentru a genera un export PDF al datelor tale, la cerere.",
          ],
        },
        {
          heading: "Unde sunt stocate datele tale",
          paragraphs: [
            "Contul tău și datele înregistrate sunt stocate în <strong>Supabase</strong> (o bază de date PostgreSQL găzduită, cu furnizor de autentificare). Serverul nostru backend rulează pe <strong>Render</strong>. Tot traficul dintre dispozitivul tău, backend-ul nostru și Supabase este criptat în tranzit (HTTPS/TLS). Accesul la baza de date este protejat prin politici Row Level Security per utilizator, iar la nivel de backend, fiecare interogare este limitată explicit la contul tău — datele altui utilizator nu sunt niciodată accesibile din contul tău.",
          ],
        },
        {
          heading: "Servicii terțe pe care le folosim",
          list: [
            "<strong>Supabase</strong> — autentificare și găzduire a bazei de date.",
            "<strong>Google Gemini API</strong> — scanarea AI a fotografiilor cu mâncare și funcția de chat AI Coach.",
            "<strong>Render</strong> — găzduirea backend-ului.",
            "<strong>Open Food Facts</strong> — căutări de coduri de bare gratuite, fără cheie (se trimite doar numărul codului de bare, fără date de cont).",
            "<strong>Cloudflare Turnstile</strong> — o verificare anti-bot opțională care poate apărea la înregistrare.",
            "<strong>Sentry</strong> — monitorizare opțională a erorilor, doar la nivel de backend, pentru a ne ajuta să reparăm defecte; nu rulează niciodată în aplicație.",
          ],
        },
        {
          heading: "Cât timp păstrăm datele tale",
          paragraphs: [
            "Jurnalele de mese și apă sunt șterse automat după <strong>7 zile</strong>, în mod continuu — aceasta este o decizie de design deliberată, nu o eroare. Jurnalele de greutate sunt păstrate pe termen nelimitat, pentru a putea vedea o tendință pe termen lung, acesta fiind scopul urmăririi greutății. Contul, obiectivele și mesele salvate sunt păstrate până când le ștergi sau îți ștergi contul.",
          ],
        },
        {
          heading: "Drepturile și opțiunile tale",
          list: [
            "<strong>Export</strong> — descarcă un PDF cu propriile tale jurnale oricând, din Setări → Datele tale.",
            "<strong>Corectare</strong> — editează sau șterge orice înregistrare individuală direct din aplicație.",
            "<strong>Ștergere</strong> — șterge-ți istoricul sau contul în întregime, oricând; vezi Politica noastră de ștergere a datelor pentru ce anume face fiecare opțiune.",
            "<strong>Dezabonare</strong> — notificările de reamintire sunt complet opționale și pot fi dezactivate oricând din Setări.",
          ],
        },
        {
          heading: "Confidențialitatea copiilor",
          paragraphs: ["Iron Log nu este destinată copiilor sub 16 ani și nu colectăm cu bună știință date de la nimeni sub această vârstă."],
        },
        {
          heading: "Transferuri internaționale de date",
          paragraphs: ["Deoarece furnizorii noștri de infrastructură (Supabase, Render, Google) operează infrastructură globală, datele tale pot fi procesate într-o altă țară decât a ta."],
        },
        {
          heading: "Modificări ale acestei politici",
          paragraphs: ["Putem actualiza această politică din când în când. Data „Ultima actualizare” de mai sus reflectă cea mai recentă revizuire."],
        },
        {
          heading: "Contactează-ne",
          paragraphs: [`Întrebări despre această politică sau despre datele tale? Scrie la <a href="mailto:${CONTACT_EMAIL}">${CONTACT_EMAIL}</a>.`],
        },
      ]),
    },
  },

  dataDeletion: {
    en: {
      title: "Data Deletion Policy",
      sections: p([
        {
          paragraphs: [
            "Iron Log gives you two built-in, self-service ways to delete your data — both directly in the app, with no need to email us. You'll find both under <strong>Settings → Danger zone</strong>.",
          ],
        },
        {
          heading: "Option 1 — Reset progress",
          paragraphs: [
            "Permanently and immediately deletes all of your logged <strong>food, water, weight, body measurement, and workout history</strong>. Your account, login, daily targets, and saved meals are left untouched — this is for wiping your history and starting fresh without losing your account or preset meals.",
          ],
        },
        {
          heading: "Option 2 — Delete account",
          paragraphs: [
            "Permanently deletes your account and <strong>everything</strong> associated with it — every log, saved meal, target, and setting, and your login itself. This cannot be undone and there is no recovery window; once confirmed, the data is gone immediately. You'll be asked to type a confirmation word before this runs, as a safeguard against accidental taps.",
          ],
        },
        {
          heading: "Can't access the app?",
          paragraphs: [`If you're unable to log in and need your account or data deleted, email <a href="mailto:${CONTACT_EMAIL}">${CONTACT_EMAIL}</a> from the address associated with your account and we'll process the deletion manually.`],
        },
        {
          heading: "Automatic deletion",
          paragraphs: [
            "Independent of anything you do manually: food and water logs are automatically deleted on a rolling 7-day basis as part of normal operation, described in our Privacy Policy.",
          ],
        },
      ]),
    },
    ro: {
      title: "Politica de ștergere a datelor",
      sections: p([
        {
          paragraphs: [
            "Iron Log îți oferă două moduri integrate, de sine stătător, pentru a-ți șterge datele — ambele direct din aplicație, fără să fie nevoie să ne scrii. Le găsești ambele în <strong>Setări → Zonă periculoasă</strong>.",
          ],
        },
        {
          heading: "Opțiunea 1 — Resetează progresul",
          paragraphs: [
            "Șterge definitiv și imediat tot istoricul tău înregistrat de <strong>mese, apă, greutate, măsurători corporale și antrenamente</strong>. Contul, autentificarea, obiectivele zilnice și mesele salvate rămân neatinse — aceasta este pentru a-ți șterge istoricul și a o lua de la capăt fără a-ți pierde contul sau mesele presetate.",
          ],
        },
        {
          heading: "Opțiunea 2 — Șterge contul",
          paragraphs: [
            "Șterge definitiv contul tău și <strong>tot</strong> ce este asociat cu el — fiecare înregistrare, masă salvată, obiectiv și setare, precum și autentificarea în sine. Această acțiune nu poate fi anulată și nu există o perioadă de recuperare; odată confirmată, datele dispar imediat. Ți se va cere să scrii un cuvânt de confirmare înainte de execuție, ca măsură de siguranță împotriva apăsărilor accidentale.",
          ],
        },
        {
          heading: "Nu poți accesa aplicația?",
          paragraphs: [`Dacă nu te poți autentifica și ai nevoie ca contul sau datele tale să fie șterse, scrie la <a href="mailto:${CONTACT_EMAIL}">${CONTACT_EMAIL}</a> de la adresa asociată contului tău, iar noi vom procesa ștergerea manual.`],
        },
        {
          heading: "Ștergere automată",
          paragraphs: [
            "Independent de orice acțiune manuală: jurnalele de mese și apă sunt șterse automat, continuu, după 7 zile, ca parte a funcționării normale, descrisă în Politica noastră de confidențialitate.",
          ],
        },
      ]),
    },
  },

  terms: {
    en: {
      title: "Terms of Service",
      sections: p([
        {
          paragraphs: [
            `These Terms of Service ("Terms") govern your use of Iron Log, developed and operated by <strong>${DEVELOPER_NAME}</strong>. By creating an account or using the app, you agree to these Terms. If you don't agree, please don't use Iron Log.`,
          ],
        },
        {
          heading: "The service",
          paragraphs: [
            "Iron Log is a personal calorie and macro tracking tool with AI-assisted food photo scanning, barcode lookup, and progress tracking. It is provided for general fitness and nutrition tracking purposes only — see our Disclaimers for important limits on what it is not.",
          ],
        },
        {
          heading: "Eligibility and accounts",
          list: [
            "You must be able to form a binding contract to create an account, and the app is not directed at children under 16.",
            "You're responsible for keeping your login credentials secure and for all activity under your account.",
            "You must provide accurate information and keep it up to date.",
          ],
        },
        {
          heading: "Acceptable use",
          paragraphs: ["You agree not to:"],
          list: [
            "Abuse, automate, or attempt to circumvent rate limits or AI usage quotas that are shared fairly across all users.",
            "Upload unlawful, abusive, or non-food content specifically to probe or attack the AI scanning system.",
            "Attempt to reverse-engineer, scrape, or gain unauthorized access to the backend, database, or other users' data.",
            "Use the service for any purpose that violates applicable law.",
          ],
        },
        {
          heading: "AI features",
          paragraphs: [
            "Food photo scanning and the AI Coach chat are powered by third-party AI models and are estimates, not guarantees of accuracy. See our Disclaimers page for the full explanation — by using these features you acknowledge and accept those limitations.",
          ],
        },
        {
          heading: "Cost",
          paragraphs: ["Iron Log is currently provided free of charge. We may introduce paid features in the future; if we do, we'll clearly communicate any change before it affects you."],
        },
        {
          heading: "Your content",
          paragraphs: [
            "You retain ownership of the data you enter (logs, photos you scan, measurements, chat messages). You grant us the limited right to process that data solely to operate the app, as described in our Privacy Policy.",
          ],
        },
        {
          heading: "Termination",
          paragraphs: [
            "You may stop using Iron Log and delete your account at any time from Settings. We may suspend or terminate access for accounts that violate these Terms, particularly the Acceptable Use section above.",
          ],
        },
        {
          heading: "Disclaimer of warranties",
          paragraphs: [
            'Iron Log is provided "as is" and "as available," without warranties of any kind, express or implied, including fitness for a particular purpose, accuracy, or uninterrupted availability. We do not guarantee the service will be error-free or always available.',
          ],
        },
        {
          heading: "Limitation of liability",
          paragraphs: [
            `To the fullest extent permitted by law, ${DEVELOPER_NAME} and Iron Log shall not be liable for any indirect, incidental, special, or consequential damages, or for any loss of data, health outcomes, or other damages arising from your use of, or inability to use, the app — including reliance on AI-estimated nutrition data. See our Disclaimers for specific health-related limitations.`,
          ],
        },
        {
          heading: "Changes to these terms",
          paragraphs: ["We may update these Terms from time to time. The \"Last updated\" date above reflects the most recent revision. Continued use of the app after a change constitutes acceptance of the new Terms."],
        },
        {
          heading: "Governing law",
          paragraphs: ["These Terms are governed by applicable law in your jurisdiction of residence, to the extent local law does not permit otherwise."],
        },
        {
          heading: "Contact us",
          paragraphs: [`Questions about these Terms? Email <a href="mailto:${CONTACT_EMAIL}">${CONTACT_EMAIL}</a>.`],
        },
      ]),
    },
    ro: {
      title: "Termeni și condiții",
      sections: p([
        {
          paragraphs: [
            `Acești Termeni și condiții ("Termenii") reglementează utilizarea Iron Log, dezvoltată și operată de <strong>${DEVELOPER_NAME}</strong>. Prin crearea unui cont sau utilizarea aplicației, ești de acord cu acești Termeni. Dacă nu ești de acord, te rugăm să nu folosești Iron Log.`,
          ],
        },
        {
          heading: "Serviciul",
          paragraphs: [
            "Iron Log este un instrument personal de urmărire a caloriilor și macronutrienților, cu scanare de fotografii asistată de AI, căutare de coduri de bare și urmărirea progresului. Este oferit exclusiv în scopuri generale de fitness și nutriție — vezi Disclaimerele noastre pentru limitele importante ale a ceea ce NU este.",
          ],
        },
        {
          heading: "Eligibilitate și conturi",
          list: [
            "Trebuie să poți încheia un contract obligatoriu pentru a crea un cont, iar aplicația nu este destinată copiilor sub 16 ani.",
            "Ești responsabil pentru păstrarea în siguranță a datelor tale de autentificare și pentru toate activitățile din contul tău.",
            "Trebuie să furnizezi informații corecte și să le păstrezi actualizate.",
          ],
        },
        {
          heading: "Utilizare acceptabilă",
          paragraphs: ["Ești de acord să nu:"],
          list: [
            "Abuzezi, automatizezi sau încerci să eviți limitele de rată sau cotele de utilizare AI, partajate echitabil între toți utilizatorii.",
            "Încarci conținut ilegal, abuziv sau care nu reprezintă mâncare, în mod specific pentru a testa sau ataca sistemul de scanare AI.",
            "Încerci să faci inginerie inversă, să extragi date sau să obții acces neautorizat la backend, baza de date sau datele altor utilizatori.",
            "Folosești serviciul în orice scop care încalcă legislația aplicabilă.",
          ],
        },
        {
          heading: "Funcții AI",
          paragraphs: [
            "Scanarea fotografiilor cu mâncare și chat-ul AI Coach sunt alimentate de modele AI terțe și reprezintă estimări, nu garanții de acuratețe. Vezi pagina noastră de Disclaimere pentru explicația completă — prin folosirea acestor funcții, recunoști și accepți aceste limitări.",
          ],
        },
        {
          heading: "Cost",
          paragraphs: ["Iron Log este oferită în prezent gratuit. Este posibil să introducem funcții cu plată în viitor; dacă vom face asta, vom comunica clar orice modificare înainte să te afecteze."],
        },
        {
          heading: "Conținutul tău",
          paragraphs: [
            "Îți păstrezi dreptul de proprietate asupra datelor pe care le introduci (jurnale, fotografii scanate, măsurători, mesaje de chat). Ne acorzi dreptul limitat de a procesa acele date exclusiv pentru a opera aplicația, conform descrierii din Politica noastră de confidențialitate.",
          ],
        },
        {
          heading: "Încetare",
          paragraphs: [
            "Poți opri folosirea Iron Log și îți poți șterge contul oricând, din Setări. Putem suspenda sau restricționa accesul conturilor care încalcă acești Termeni, în special secțiunea Utilizare acceptabilă de mai sus.",
          ],
        },
        {
          heading: "Excluderea garanțiilor",
          paragraphs: [
            'Iron Log este oferită "ca atare" și "ca disponibilă", fără garanții de niciun fel, exprese sau implicite, inclusiv adecvarea pentru un anumit scop, acuratețea sau disponibilitatea neîntreruptă. Nu garantăm că serviciul va fi lipsit de erori sau mereu disponibil.',
          ],
        },
        {
          heading: "Limitarea răspunderii",
          paragraphs: [
            `În limita maximă permisă de lege, ${DEVELOPER_NAME} și Iron Log nu vor fi răspunzători pentru daune indirecte, incidentale, speciale sau subsecvente, sau pentru pierderea de date, rezultate asupra sănătății sau alte daune rezultate din utilizarea sau imposibilitatea de a utiliza aplicația — inclusiv încrederea în date nutriționale estimate de AI. Vezi Disclaimerele noastre pentru limitări specifice legate de sănătate.`,
          ],
        },
        {
          heading: "Modificări ale acestor termeni",
          paragraphs: ["Putem actualiza acești Termeni din când în când. Data „Ultima actualizare” de mai sus reflectă cea mai recentă revizuire. Continuarea utilizării aplicației după o modificare reprezintă acceptarea noilor Termeni."],
        },
        {
          heading: "Legea aplicabilă",
          paragraphs: ["Acești Termeni sunt guvernați de legislația aplicabilă din jurisdicția ta de reședință, în măsura în care legea locală nu permite altfel."],
        },
        {
          heading: "Contactează-ne",
          paragraphs: [`Întrebări despre acești Termeni? Scrie la <a href="mailto:${CONTACT_EMAIL}">${CONTACT_EMAIL}</a>.`],
        },
      ]),
    },
  },

  disclaimers: {
    en: {
      title: "Medical & AI Disclaimers",
      sections: p([
        {
          paragraphs: ["Please read this carefully before relying on anything Iron Log tells you."],
        },
        {
          heading: "Not medical advice",
          paragraphs: [
            "Iron Log is a self-tracking tool, not a medical device and not a substitute for professional medical, nutritional, or fitness advice. Nothing in the app — calorie/macro targets, AI Coach responses, or scanned nutrition estimates — should be treated as a diagnosis, treatment, or personalized medical recommendation. Always consult a doctor, registered dietitian, or qualified professional before starting any diet, exercise program, or making changes based on a pre-existing medical condition, pregnancy, eating disorder history, or similar.",
          ],
        },
        {
          heading: "Targets are estimates",
          paragraphs: [
            "Suggested calorie and macro targets are calculated from standard formulas using the information you provide (weight, height, age, sex, activity level). These formulas produce population-level estimates — your actual needs can differ meaningfully based on individual metabolism, health conditions, and other factors the formula can't account for.",
          ],
        },
        {
          heading: "AI can make mistakes — verify before you rely on it",
          paragraphs: [
            "Food photo scanning and the AI Coach are powered by AI models that can misidentify food, misjudge portion size, or occasionally produce plausible-looking but incorrect nutrition numbers (\"hallucinate\"). <strong>Always visually check an AI-suggested food, portion, and macro breakdown against what you actually ate — and against the package label when one exists — before trusting it</strong>, especially for anything that matters medically.",
            "This matters most if you manage a food allergy, intolerance, or a medical condition that depends on precise nutrition: do not rely on an AI-estimated ingredient list or macro breakdown to make a safety decision. When in doubt, check the label yourself or leave that item out.",
          ],
        },
        {
          heading: "No liability for health outcomes",
          paragraphs: ["We are not responsible for any health outcome, injury, or other consequence resulting from decisions made using information from the app, including AI-generated estimates."],
        },
        {
          heading: "In an emergency",
          paragraphs: ["Iron Log is not monitored for emergencies and cannot respond to one. If you are experiencing a medical emergency, contact your local emergency services immediately — not the app."],
        },
      ]),
    },
    ro: {
      title: "Disclaimere medicale și AI",
      sections: p([
        {
          paragraphs: ["Te rugăm să citești cu atenție înainte de a te baza pe orice îți spune Iron Log."],
        },
        {
          heading: "Nu este sfat medical",
          paragraphs: [
            "Iron Log este un instrument de auto-monitorizare, nu un dispozitiv medical și nu înlocuiește sfatul medical, nutrițional sau de fitness profesionist. Nimic din aplicație — obiectivele de calorii/macronutrienți, răspunsurile AI Coach sau estimările nutriționale scanate — nu trebuie tratat ca un diagnostic, tratament sau recomandare medicală personalizată. Consultă întotdeauna un medic, un nutriționist autorizat sau un profesionist calificat înainte de a începe orice dietă, program de exerciții sau de a face schimbări pe baza unei afecțiuni medicale preexistente, sarcini, istoric de tulburări alimentare sau similar.",
          ],
        },
        {
          heading: "Obiectivele sunt estimări",
          paragraphs: [
            "Obiectivele sugerate de calorii și macronutrienți sunt calculate din formule standard, folosind informațiile pe care le furnizezi (greutate, înălțime, vârstă, sex, nivel de activitate). Aceste formule produc estimări la nivel de populație — nevoile tale reale pot diferi semnificativ în funcție de metabolismul individual, afecțiuni de sănătate și alți factori pe care formula nu îi poate lua în calcul.",
          ],
        },
        {
          heading: "AI poate greși — verifică înainte să te bazezi pe el",
          paragraphs: [
            "Scanarea fotografiilor cu mâncare și AI Coach sunt alimentate de modele AI care pot identifica greșit alimentul, pot estima greșit dimensiunea porției sau pot produce ocazional cifre nutriționale plauzibile, dar incorecte („halucinații”). <strong>Verifică întotdeauna vizual alimentul, porția și defalcarea macronutrienților sugerate de AI față de ce ai mâncat de fapt — și față de eticheta produsului, atunci când există — înainte de a avea încredere în ele</strong>, mai ales pentru orice contează din punct de vedere medical.",
            "Acest lucru contează cel mai mult dacă gestionezi o alergie alimentară, o intoleranță sau o afecțiune medicală care depinde de nutriție precisă: nu te baza pe o listă de ingrediente sau o defalcare de macronutrienți estimată de AI pentru a lua o decizie de siguranță. În caz de îndoială, verifică eticheta singur sau exclude acel aliment.",
          ],
        },
        {
          heading: "Fără răspundere pentru rezultate asupra sănătății",
          paragraphs: ["Nu suntem responsabili pentru niciun rezultat asupra sănătății, vătămare sau altă consecință rezultată din decizii luate folosind informații din aplicație, inclusiv estimări generate de AI."],
        },
        {
          heading: "În caz de urgență",
          paragraphs: ["Iron Log nu este monitorizată pentru urgențe și nu poate răspunde uneia. Dacă te confrunți cu o urgență medicală, contactează imediat serviciile locale de urgență — nu aplicația."],
        },
      ]),
    },
  },
};

export function getLastUpdated() {
  return LAST_UPDATED;
}

export function getLegalDoc(docId, lang) {
  const doc = LEGAL_DOCS[docId];
  if (!doc) return null;
  return doc[lang] || doc.en;
}

// Shared renderer — used by both the in-app sheet (innerHTML target already
// exists in the sheet's own container) and the standalone pages (which build
// a full document around this same fragment).
export function renderLegalSectionsHtml(sections) {
  return sections
    .map((section) => {
      let html = "";
      if (section.heading) html += `<h3>${section.heading}</h3>`;
      if (section.paragraphs) html += section.paragraphs.map((text) => `<p>${text}</p>`).join("");
      if (section.list) html += `<ul>${section.list.map((item) => `<li>${item}</li>`).join("")}</ul>`;
      return html;
    })
    .join("");
}
